# Site Settings
lang: en
title: Robonigiri
tagline: PIE Final Project
email: sidneyt27@gmail.com
description: >
  Project documentation site for the first automatic onigiri maker.
baseurl: "/pie-2023-03/robonigiri"
url: "olincollege.github.io"
permalink: pretty
favicon: https://i.imgur.com/QuEpqQb.png
gh_sponsor: sidkofi
hide_share_buttons: true
remote_theme: chrisrhymes/bulma-clean-theme
theme: bulma-clean-theme
paginate: 5
paginate_path: "/blog/page:num"


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Sid"
      layout: post

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
